package steps;

import java.util.HashMap;
import java.util.Map;

import org.junit.Assert;

import challenges.EmailAdapter;
import challenges.EmailApp;
import challenges.UserAgent;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;
import flow.Engine;
import flow.IAdapter;

/**
 * Steps are the sequence of the stages, automatically generated by the Cucumber
 * framework
 * 
 * @author lucas
 *
 */
public class EmailSteps {

	private Engine engine;

	@Given("^A User sends an \"([^\"]*)\" message$")
	public void aUserSendsAnMessage(String message) throws Throwable {
		Map<String, IAdapter> adapters = new HashMap();
		adapters.put("EMAIL", new EmailAdapter());
		engine = new Engine(new UserAgent(message), adapters, new EmailApp());

	}

	@When("^The message is converted by the Adapter$")
	public void theMessageIsConvertedByTheAdapter() throws Throwable {
		engine.run();
	}

	@Then("^The Message server should contain the \"([^\"]*)\" message in the queue$")
	public void theMessageServerShouldContainTheMessageInTheQueue(String message) throws Throwable {
		EmailApp app = (EmailApp) engine.getApp();
		Assert.assertEquals(message, app.popMessage());
		System.out.println(app.popMessage() + " message sent successfully! ");
	}

}
